name: TESTCI

on:
  push:     
    branches:
      - master 
  pull_request:
    branches:
      - master
  
jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] 

    steps:
    - uses: actions/checkout@v1
    - name: Build static test
      run: |
        set -e
        mkdir build_static
        cd build_static
        cmake ..
        make

    - name: Test
      run: |
        echo GITHUB_WORKFLOW is $GITHUB_WORKFLOW
        echo HOME $HOME
        echo GITHUB_REPOSITORY $GITHUB_REPOSITORY
        build_static/Hello
        echo GITHUB_WORKFLOW is $GITHUB_WORKFLOW

