name: TESTCI

on:
  push:     
    branches:
      - master 
  pull_request:
    branches:
      - master
  
jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [windows-latest] ## [ubuntu-latest, windows-latest, macos-latest] 

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Build static test
      env:
        RUNOS: ${{ runner.os }}
      if: runner.os == 'linux' || runner.os == 'macos'
      shell: bash
      run: |
        set -e
        c++ --version               
        mkdir build_static
        cd build_static
        cmake ..
        make
        echo "THIS IS ON : " $RUNOS

    - name: Build static test on windows
      if: runner.os == 'windows'
      shell: cmd
      run: |
        set -e
        echo "====On windows"
        echo %PATH%
        dir c:\
        dir "c:\Program Files (x86)"
        echo "====c++"
        c++ --version               
        echo "====current dir"
        set mydir=%CD%
        echo %mydir%
        echo "=====find file on c"
        chdir c:\
        set myd=%CD%
        echo %myd%
        dir vcvarsall.bat /s
        echo "=====find file on d"
        chdir d:\ 
        set mydir=%CD%
        echo %mydir%
        dir vcvarsall.bat /s

#        echo "====Creating dir "
#        mkdir build_static
#        cd build_static
#        echo "====install ninja"
#        pip install ninja
#        which ninja
#        echo "====vcvarsall.bat"
#        find . -name "vcvarsall.bat"
#        echo "====cmake"
#        cmake -G Ninja -DCMAKE_C_COMPILER="cl.exe" -DCMAKE_CXX_COMPILER="cl.exe" ..
#        ninja -k 0 all
#        echo "THIS IS ON LINUX" ${runner.os}

    - name: Test
##      if: contains(runner.os,'Linux')
      run: |
        echo GITHUB_WORKFLOW is $GITHUB_WORKFLOW
        echo HOME $HOME
        echo GITHUB_ACTION $GITHUB_ACTION
        echo GITHUB_ACTIONS $GITHUB_ACTIONS
        echo GITHUB_REPOSITORY $GITHUB_REPOSITORY
        echo GITHUB_EVENT_NAME $GITHUB_EVENT_NAME
        echo GITHUB_EVENT_PATH $GITHUB_EVENT_PATH
        echo GITHUB_WORKSPACE  $GITHUB_WORKSPACE
        echo GITHUB_SHA        $GITHUB_SHA
        echo GITHUB_REF        $GITHUB_REF
        echo "--------"
        build_static/Hello
        echo GITHUB_WORKFLOW is $GITHUB_WORKFLOW
        echo "LINUX AGAIN" {{ runner.os }}

